[package]
name = "plastercast"
version = "0.1.0"
authors = ["Kai Willadsen <kai.willadsen@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4.6"
mdns = "0.3.0"

[lib]
name = "castwrapper"
path = "src/lib.rs"
